Weapons:
  - ==: OverheatWeapon
    Material: TNT
    Directions:
      - "0, 0, 0"
      - "1, 0, 0"
      - "-1, 0, 0"
      - "0, 0, 1"
      - "0, 0, -1"
      - "1, 0, 1"
      - "1, 0, -1"
      - "-1, 0, 1"
      - "-1, 0, -1"
      - "0, 1, 0"
      - "0, -1, 0"
    HeatRate: 42
    HeatDissipation: 21
    Disasters:
      - ==: ExplosionDisaster
        ExplosionPower: 4.0
        Threshold: 1.5
        RandomChance: 0.5